language: python
python:
  - "3.7.3"
  - "3.6.7"
  - "2.7.15"
addons:
  - sqlite3: "3.8.3"
  
env: 
    -DJANGO=2.2.1

install:
      - pip install -r requirements.txt
      - pip install coverage
      - python manage.py migrate
    
script:
       - python manage.py test apiapp

